#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &

# fix some Java applications
# wmname LG3D

# workspaces
bspc monitor primary -d 1 2 3 4 5 6 7
bspc monitor HDMI-A-0 -d 8  # TODO: multiple monitors

bspc config focus_follows_pointer false

# Window borders (Auto-Generate)
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 3
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# fix pointer
xsetroot -cursor_name left_ptr

# gaps
bspc config gapless_monocle false
bspc config window_gap 10

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# rules
bspc rule -a feh state=floating
bspc rule -a TelegramDesktop:telegram-desktop state=floating desktop='^1' rectangle=477x1054+1427+10 follow=on
bspc rule -a Google-chrome state=floating desktop='^1' rectangle=1401x1054+10+10 follow=on
bspc rule -a Alacritty desktop='^2' follow=on
bspc rule -a Thunar desktop='^3' follow=on
bspc rule -a jetbrains-pycharm desktop='^4' follow=on
bspc rule -a Lutris desktop='^5' follow=on
bspc rule -a YandexMusic desktop='^3' follow=on
bspc rule -a Deluge desktop='^6' follow=off
# bspc rule -a firefox state=floating
# bspc rule -a firefox desktop='^2' follow=on

# start resources
xrdb merge ~/.Xresources

# python script to always initialize with a different wallpaper:
# TODO: Add loading of basic scripts
~/.config/bspwm/scripts/launch.sh &
~/.config/polybar/launch.sh

# launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# launch battery tracker and redshift
pkill battery-alert; ~/.local/bin/battery-alert &
pgrep -x redshift > /dev/null || redshift &

# start compositor
picom --config $HOME/.config/bspwm/picom_configurations/1.conf &

# autostart
flameshot &
telegram-desktop &
google-chrome-stable &
